package org.androidpn.server.model;
// Generated 2012-10-19 9:29:18 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * TtUser generated by hbm2java
 */
public class TtUser  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long id;
     private String username;
     private String pwd;
     private String imeicode;
     private String simcode;
     private String realname;
     private long point;
     private long pointall;
     private double virtualmoney;
     private BigDecimal usertype;
     private BigDecimal userlevel;
     private Date lastlogintime;
     private Date signtime;
     private BigDecimal loginstatus;
     private BigDecimal status;
     private String devicetokenapple;
     private String devicetokenandroid;
     private String spare1;
     private String spare2;
     private BigDecimal agentid;    
     private String phonenumber;
     private String email;
     private BigDecimal lastloginos;
     private BigDecimal wantmessageios;
     private BigDecimal wantmessageandroid;
     
    public TtUser() {
    }

	
    public TtUser(long id, String username, String imeicode, long point, long pointall, double virtualmoney, 
            BigDecimal usertype, Date lastlogintime, Date signtime, BigDecimal loginstatus, BigDecimal status
            ,BigDecimal lastloginos,BigDecimal wantmessageios,BigDecimal wantmessageandroid) {
        this.id = id;
        this.username = username;
        this.imeicode = imeicode;
        this.point = point;
        this.pointall = pointall;
        this.virtualmoney = virtualmoney;
        this.usertype = usertype;
        this.lastlogintime = lastlogintime;
        this.signtime = signtime;
        this.loginstatus = loginstatus;
        this.status = status;
        this.lastloginos = lastloginos;
        this.wantmessageios = wantmessageios;
        this.wantmessageandroid = wantmessageandroid;
    }
    public TtUser(long id, String username, String pwd, String imeicode, String simcode, String realname, long point, 
            long pointall, double virtualmoney, BigDecimal usertype, BigDecimal userlevel, Date lastlogintime, Date signtime, 
            BigDecimal loginstatus, BigDecimal status, String devicetokenapple, String spare1, String spare2,BigDecimal agentid,String phonenumber,String email,
            String devicetokenandroid,BigDecimal lastloginos,BigDecimal wantmessageios,BigDecimal wantmessageandroid) {
       this.id = id;
       this.username = username;
       this.pwd = pwd;
       this.imeicode = imeicode;
       this.simcode = simcode;
       this.realname = realname;
       this.point = point;
       this.pointall = pointall;
       this.virtualmoney = virtualmoney;
       this.usertype = usertype;
       this.userlevel = userlevel;
       this.lastlogintime = lastlogintime;
       this.signtime = signtime;
       this.loginstatus = loginstatus;
       this.status = status;
       this.devicetokenapple = devicetokenapple;
       this.spare1 = spare1;
       this.spare2 = spare2;
       this.agentid = agentid;  
       this.phonenumber = phonenumber;
       this.email = email;
       this.devicetokenandroid = devicetokenandroid;
       this.lastloginos = lastloginos;
       this.wantmessageios = wantmessageios;
       this.wantmessageandroid = wantmessageandroid;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPwd() {
        return this.pwd;
    }
    
    public void setPwd(String pwd) {
        this.pwd = pwd;
    }
    public String getImeicode() {
        return this.imeicode;
    }
    
    public void setImeicode(String imeicode) {
        this.imeicode = imeicode;
    }
    public String getSimcode() {
        return this.simcode;
    }
    
    public void setSimcode(String simcode) {
        this.simcode = simcode;
    }
    public String getRealname() {
        return this.realname;
    }
    
    public void setRealname(String realname) {
        this.realname = realname;
    }
    public long getPoint() {
        return this.point;
    }
    
    public void setPoint(long point) {
        this.point = point;
    }
    public long getPointall() {
        return this.pointall;
    }
    
    public void setPointall(long pointall) {
        this.pointall = pointall;
    }
    public double getVirtualmoney() {
        return this.virtualmoney;
    }
    
    public void setVirtualmoney(double virtualmoney) {
        this.virtualmoney = virtualmoney;
    }
    public BigDecimal getUsertype() {
        return this.usertype;
    }
    
    public void setUsertype(BigDecimal usertype) {
        this.usertype = usertype;
    }
    public BigDecimal getUserlevel() {
        return this.userlevel;
    }
    
    public void setUserlevel(BigDecimal userlevel) {
        this.userlevel = userlevel;
    }
    public Date getLastlogintime() {
        return this.lastlogintime;
    }
    
    public void setLastlogintime(Date lastlogintime) {
        this.lastlogintime = lastlogintime;
    }
    public Date getSigntime() {
        return this.signtime;
    }
    
    public void setSigntime(Date signtime) {
        this.signtime = signtime;
    }
    public BigDecimal getLoginstatus() {
        return this.loginstatus;
    }
    
    public void setLoginstatus(BigDecimal loginstatus) {
        this.loginstatus = loginstatus;
    }
    public BigDecimal getStatus() {
        return this.status;
    }
    
    public void setStatus(BigDecimal status) {
        this.status = status;
    }
    
    public String getSpare1() {
        return this.spare1;
    }
    
    public void setSpare1(String spare1) {
        this.spare1 = spare1;
    }
    public String getSpare2() {
        return this.spare2;
    }
    
    public void setSpare2(String spare2) {
        this.spare2 = spare2;
    }

    public BigDecimal getAgentid() {
        return this.agentid;
    }
    
    public void setAgentid(BigDecimal agentid) {
        this.agentid = agentid;
    }

    public String getPhonenumber() {
        return phonenumber;
    }

    public void setPhonenumber(String phonenumber) {
        this.phonenumber = phonenumber;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getDevicetokenapple() {
        return devicetokenapple;
    }

    public void setDevicetokenapple(String devicetokenapple) {
        this.devicetokenapple = devicetokenapple;
    }

    public String getDevicetokenandroid() {
        return devicetokenandroid;
    }

    public void setDevicetokenandroid(String devicetokenandroid) {
        this.devicetokenandroid = devicetokenandroid;
    }

    public BigDecimal getLastloginos() {
        return lastloginos;
    }

    public void setLastloginos(BigDecimal lastloginos) {
        this.lastloginos = lastloginos;
    }

    public BigDecimal getWantmessageios() {
        return wantmessageios;
    }

    public void setWantmessageios(BigDecimal wantmessageios) {
        this.wantmessageios = wantmessageios;
    }

    public BigDecimal getWantmessageandroid() {
        return wantmessageandroid;
    }

    public void setWantmessageandroid(BigDecimal wantmessageandroid) {
        this.wantmessageandroid = wantmessageandroid;
    }


}


